### ISSUE TITLE
Make hiera optional

### ISSUE THREAD

**Issue by tuxmea** [epost-dev/opennebula-puppet-module#128]
ATM there are many explicit hiera calls.
I want to allow users to decide by themselves by making use of puppet 3 automatic data bindings.
This means a larger impact for existing users as we have to change the API (init.pp).
I will prepare a pull request for this one after I finished the types and providers.
But: this change definitely needs a major version bump.

**Comment by rwaffen** [comment]
okay, we will keep that in mind...
