### ISSUE TITLE
Error when trying to create an ETHER network

### ISSUE THREAD

**Issue by gdhgdhgdh** [epost-dev/opennebula-puppet-module#138]
Hi, using one 4.10 on CentOS 7 (a simple PR coming your way to support yum repos / changed packages), I'm trying to define a simple network:

```
  onevnet { 'tenlocal':
    ensure       => present,
    bridge       => 'br0',
    addressrange => {
      'macstart'  => '02:00:16:90:01:01',
      'size' => '200',
      'type' => 'ETHER',
    }
  }
```

However I'm getting this error from Puppet 3.7.4:

```
Error: Invalid parameter network_start(:network_start)
Error: /Stage[main]/Roles::Default/Onevnet[tenlocal]/ensure: change from absent to present failed: Invalid parameter network_start(:network_start)
```

I don't understand this error since I didn't define `network_start` - I have an external DHCP server and am using the `dummy` virtual net driver to just bridge VMs with the rest of my network. This is working well on a manually-configured installation, and I would like to Puppetise the setup.

Cheers,
Gavin.

**Comment by tuxmea** [comment]
Are you using the module from puppetforge or from github?
The onevnet type/provider is not yet fully working.
I still have troubles with creating networks.

**Comment by gdhgdhgdh** [comment]
Hello :) I just realised I did not reply to this.

I'm tracking the current GitHub version of the module (well, OK I'm tracking the one in my own repo https://github.com/gdhgdhgdh/opennebula-puppet-module.git ).

OK no worries. I'm learning Ruby and I'll help if I can.

**Comment by tuxmea** [comment]
@gdhgdhgdh the ether network type will come in my next PR.
