### ISSUE TITLE
Documentation does not mention puppetlabs-stdlib

### ISSUE THREAD

**Issue by mattthias** [epost-dev/opennebula-puppet-module#192]
The documentation should mention that puppetlabs-stdlib is needed. If the module is not present puppet fails with 

      Error: Unknown function validate_string at /root/modules/one/manifests/params.pp:163 on node centos6

**Comment by rwaffen** [comment]
That's right. At the moment only the metadata.json has this info. At the forge you also get this info, but the main site should do this too. 

You may hand in a PR and fix it yourself or wait until someone other has the time to do so...

btw.: if you use the forge with `puppet module install epostdev-one`  you will get all the needed modules which are referenced in the metadata.json
