### ISSUE TITLE
new kvm driver config handling continuously appends and breaks syntax

### ISSUE THREAD

**Issue by jtriley** [epost-dev/opennebula-puppet-module#197]
The recent change to kvm driver config isn't working properly. When both the kvm emulator and nic settings are specified it doesn't idempotently make the updates and instead constantly appends to the file every time puppet runs. Even worse it's appending the wrong output (ie `[]` on a line by itself) which causes a syntax error:

```
[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm

[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm

[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm

[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm
```

Error in logs:

```
Thu Sep 10 11:23:43 2015 [Z0][VMM][I]:  Loading driver: kvm (KVM)
Thu Sep 10 11:23:43 2015 [Z0][VMM][E]: Error loading driver configuration file /etc/one/vmm_exec/vmm_exec_kvm.conf : syntax error, unexpected CBRACKET, expecting $end at line 60, columns 2797:2799
```

**Comment by rwaffen** [comment]
ah damn, but i think i have a fix for that.

**Comment by rwaffen** [comment]
@escalate please review this change with the team and merge … i'm off now for my vacation :smile:

**Comment by jtriley** [comment]
This was due to an old version of ininfile (1.0.3). Upgrading to the latest 1.4.2 version solved the issue. Perhaps we should require inifile >= 1.4.2?
