### ISSUE TITLE
OpenNebula 4.14 support

### ISSUE THREAD

**Issue by jnoss** [epost-dev/opennebula-puppet-module#222]
We'd like to support OpenNebula 4.14, so are working on templating the config files. There are a number of differences between 4.14 and 4.12, so we propose the following:

- what is currently the master branch becomes a 4.12 branch
- the master then becomes 4.14
- the master branch is 4.14 until 4.15 is released, and then we make a 4.14 branch

Let us know your thoughts regarding that.  For now we've got a work in progress of updating the config template files on a fasrc/opennebula_4_14 branch (comparison view https://github.com/epost-dev/opennebula-puppet-module/compare/master...fasrc:opennebula_4_14)

Another option is to version the template directory - ie 

    └── templates
        ├── 4.12
        ├── 4.14
And then in paths to template files in puppet code:

    file { '/etc/one/oned.conf':
      ensure  => file,
      owner   => 'root',
      mode    => '0640',
      content => template("one/${one_version}/oned.conf.erb"),
    }

This approach has the benefit of a single branch to support all versions, but might make the code more complicated if we have to split anything out by version other than templates.

Thoughts?

**Comment by rwaffen** [comment]
i think the branching-thing would be okay…. but have to discuss this with the team!

**Comment by jnoss** [comment]
@rwaffen any thoughts?

**Comment by rwaffen** [comment]
currently i'm on vacation… but maybe @sebastian-su or @gerald1248 have something to say to this …

**Comment by tuxmea** [comment]
The difficulty with versioned template files is that you have to manage multiple versions of the same configuration file.

A more Puppet-like approach would be to use the version variable inside the template.
Another option would be to split up the template for a config file into multiple smaller segments.
```
  content => template('template_header', 'template_body1','template_body2','template-footer'),
 ```

**Comment by sebastian-su** [comment]
finally merged, shall I close the issue?

**Comment by jnoss** [comment]
Great, thanks!
