### ISSUE TITLE
Module QuoVadis?

### ISSUE THREAD

**Issue by SimonHoenscheid** [epost-dev/opennebula-puppet-module#226]
Hey Folks,

I have been using this module since a long time and I would like to use it in the future. The main problem for me is that this module is nailed to puppet 3.1 and also it is not up to date to the Puppetlabs Styleguide anymore. 

I thought about the following steps to modify this module:
* Update it to the current Styleguide for Puppet 3 and ensure ist is running with Puppet 3.latest version
* Update supported OS Plattforms
* create a new major release
* rewrite the code to make it compliant with features introduced by Puppet 4

Please let me know what you think and what you guys at epost have in mind about this module in the future

**Comment by SimonHoenscheid** [comment]
@nmesstorff @rwaffen @escalate @oliverwehrens @tuxmea

**Comment by rwaffen** [comment]
Prepare some changes and than let's see if someone is in the mood to merge. I'm no longer at Deutsche Post, so i can't merge anything.

**Comment by tuxmea** [comment]
It would be great having Puppet 4 support.
But I doubt that Puppet 4 is somewhere near actual work scope at epost (which are the only people with merge rights) - you see how "active" the maintainers even answer on your request.
My advise: prepare changes, create a PR. If no one answers / merges within reasonable time: fork it and upload a new version under your name to the forge.

**Comment by sebastian-su** [comment]
Hi @SimonHoenscheid,
as @tuxmea already pointed out, Puppet 4 is not really in the scope right now. Other than that I'll ask the ePost guys about the other issues, lets see what we can work on.
However if you like to work in it, feel free to create PRs.

**Comment by tuxmea** [comment]
Hi @SimonHoenscheid travis does puppet 4 tests.
Are you willing to work on styleguide?
Should we keep this issue open?

**Comment by SimonHoenscheid** [comment]
Hi @tuxmea , I am willing to. I would suggest we close this issue. I will break down the work to single tasks.
