### ISSUE TITLE
Opennebula 5.x support

### ISSUE THREAD

**Issue by mguezuraga** [epost-dev/opennebula-puppet-module#236]
Opennebula 5 was released on Jun, 15th 2016. Could we get compatibility for it?

**Comment by Xylakant** [comment]
Hi @mguezuraga , an update to Opennebula 5 at epost is expected to happen somewhere in 2017. Until then we're probably not going to invest too much effort in working on that front. We'd welcome and merge working and tested pull requests and deploy them to puppetforge.

Work on that is already done by @jnoss  in this branch https://github.com/fasrc/opennebula-puppet-module/tree/opennebula_5, so if you're willing to contribute code or testing, that would probably be the best place to start.

Until then we'll close this issue.
