### ISSUE TITLE
Test fail on ruby >= 1.9.3

### ISSUE THREAD

**Issue by Xylakant** [epost-dev/opennebula-puppet-module#252]
seems like a new rake version is to blame. See https://travis-ci.org/epost-dev/opennebula-puppet-module/builds/173844223

**Comment by tuxmea** [comment]
No. It is the combination of getting a newer rake version and pinning rspec to <3.
We can either drop Puppet 3 support and unpin rspec or pin rake to <12.

**Comment by Xylakant** [comment]
Fixed via #257
