### ISSUE TITLE
Use of the HTTP Protocol

### ISSUE THREAD

**Issue by akondasif** [epost-dev/opennebula-puppet-module#261]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts. I found instances where the HTTP protocol is used instead of HTTPS (HTTP with TLS). I think this is a smell, and I was wondering why HTTP is used? Is it because of lack of tool support? I am trying to find out if developers are forced to adopt bad practices due to lack of tool support when it comes to the HTTPS protocol.   

Any feedback is appreciated.  

Source: https://github.com/epost-dev/opennebula-puppet-module/blob/master/manifests/params.pp (line#142)

**Comment by Xylakant** [comment]
This is the official url for debian mirrors, all updates pulled from that URL would be GPG signed anyways. There's no code-smell at all.

Please evaluate all places that your (obviously automated) script finds before opening tickets.
